"""DNS configuration for containers.

Writes /etc/resolv.conf inside the container rootfs before it starts,
giving containers DNS resolution without requiring a container-local
nameserver.

Default nameservers: 1.1.1.1 (Cloudflare) and 8.8.8.8 (Google).
"""

from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)

DEFAULT_NAMESERVERS = ["1.1.1.1", "8.8.8.8"]


def write_resolv_conf(
    rootfs: Path,
    nameservers: list[str] | None = None,
    search_domains: list[str] | None = None,
) -> None:
    """Write /etc/resolv.conf inside the container rootfs.

    Creates /etc/resolv.conf with the given nameservers. If the /etc
    directory doesn't exist it is created.

    Args:
        rootfs:         Path to the container's rootfs directory (host-side).
        nameservers:    List of DNS server IPs. Defaults to DEFAULT_NAMESERVERS.
        search_domains: Optional search domain list.
    """
    ns_list = nameservers or DEFAULT_NAMESERVERS
    etc_dir = rootfs / "etc"
    etc_dir.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [
        "# Generated by PyBox",
    ]
    for ns in ns_list:
        lines.append(f"nameserver {ns}")
    if search_domains:
        lines.append(f"search {' '.join(search_domains)}")

    resolv_conf = etc_dir / "resolv.conf"
    resolv_conf.write_text("\n".join(lines) + "\n")
    logger.debug("Written resolv.conf to %s with nameservers: %s", resolv_conf, ns_list)
